---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lyrics-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lyrics-service
  template:
    metadata:
      labels:
        app: lyrics-service
    spec:
      containers:
        - name: lyrics-service
          image: lyrics-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: lyrics-service
spec:
  selector:
    app: lyrics-service
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: composition-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: composition-service
  template:
    metadata:
      labels:
        app: composition-service
    spec:
      containers:
        - name: composition-service
          image: composition-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: composition-service
spec:
  selector:
    app: composition-service
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: car-service
  template:
    metadata:
      labels:
        app: car-service
    spec:
      containers:
        - name: car-service
          image: car-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5003
---
apiVersion: v1
kind: Service
metadata:
  name: car-service
spec:
  selector:
    app: car-service
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
---









apiVersion: apps/v1
kind: Deployment
metadata:
  name: mixing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mixing-service
  template:
    metadata:
      labels:
        app: mixing-service
    spec:
      containers:
        - name: mixing-service
          image: mixing-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5007
---
apiVersion: v1
kind: Service
metadata:
  name: mixing-service
spec:
  selector:
    app: mixing-service
  ports:
    - protocol: TCP
      port: 5007
      targetPort: 5007
---










apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      containers:
        - name: orchestrator
          image: orchestrator:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: orchestrator
spec:
  type: NodePort
  selector:
    app: orchestrator
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000
